pipeline {

    agent {
        docker {
            image 'hashicorp/terraform:latest'
            args '--entrypoint=""'
            reuseNode true
        }
    }

    parameters {
        choice(
            name: 'ENVIRONMENT',
            choices: ['sit', 'ppte', 'prod'],
            description: 'Select the environment'
        )
    }

    stages {

        stage('Terraform Init') {
            steps {
                sh '''
                    terraform version
                    terraform init
                '''
            }
        }

        stage('Terraform Plan') {
            steps {
                sh """
                    echo "Selected Environment: ${params.ENVIRONMENT}"

                    terraform plan \
                        -var-file="${params.ENVIRONMENT}.tfvars"
                """
            }
        }

        stage('Approval') {
            steps {
                input(
                    message: "Do you want to apply changes for ${params.ENVIRONMENT}?",
                    ok: 'Apply'
                )
            }
        }

        stage('Terraform Apply') {
            steps {
                sh """
                    terraform apply \
                        -var-file="${params.ENVIRONMENT}.tfvars" \
                        -auto-approve
                """
            }
        }

        stage('Terraform Output') {
            steps {
                sh 'terraform output'
            }
        }
    }
}
