pipeline {

    agent {
        label "${params.ENVIRONMENT == 'sit' ? 'dev' : 
                params.ENVIRONMENT == 'ppte' ? 'ppte' : 
                params.ENVIRONMENT == 'prod' ? 'prod' : 'dev'}"
    }

    parameters {
        choice(
            name: 'ENVIRONMENT',
            choices: ['sit', 'ppte', 'prod'],
            description: 'Select the environment'
        )
    }

    stages {

        stage('Show Agent') {
            steps {
                sh '''
                    echo "Running on:"
                    hostname
                    echo "Environment: $ENVIRONMENT"
                '''
            }
        }

        stage('Terraform Init') {
            steps {
                dir('day1') {
                    sh '''
                        terraform version
                        terraform init
                    '''
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('day1') {
                    sh """
                        terraform plan -var-file=${params.ENVIRONMENT}.tfvars
                    """
                }
            }
        }

        stage('Approval') {
            steps {
                input(
                    message: "Do you want to apply Terraform changes for ${params.ENVIRONMENT}?",
                    ok: 'Apply'
                )
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('day1') {
                    sh """
                        terraform apply -auto-approve -var-file=${params.ENVIRONMENT}.tfvars
                    """
                }
            }
        }

        stage('Terraform Output') {
            steps {
                dir('day1') {
                    sh 'terraform output'
                }
            }
        }
    }
}
