pipeline {

    agent {
        docker {
            image 'hashicorp/terraform:latest'
            args '--entrypoint="" --user 0'
            reuseNode true
        }
    }

    parameters {
        choice(
            name: 'ENVIRONMENT',
            choices: ['sit', 'ppte', 'prod'],
            description: 'Select the environment'
        )
    }

    stages {

        stage('Terraform Init') {
            steps {
                dir('day2') {
                    withCredentials([
                        usernamePassword(
                            credentialsId: 'aws-credentials',
                            usernameVariable: 'AWS_ACCESS_KEY_ID',
                            passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                        )
                    ]) {
                        sh '''
                            echo "Terraform Version:"
                            terraform version

                            echo "Initializing Terraform..."
                            terraform init
                        '''
                    }
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('day2') {
                    withCredentials([
                        usernamePassword(
                            credentialsId: 'aws-credentials',
                            usernameVariable: 'AWS_ACCESS_KEY_ID',
                            passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                        )
                    ]) {
                        sh """
                            echo "Environment: ${params.ENVIRONMENT}"

                            terraform plan \
                              -var-file=${params.ENVIRONMENT}.tfvars \
                              -out=tfplan
                        """
                    }
                }
            }
        }

        stage('Approval') {
            steps {
                input(
                    message: "Do you want to APPLY Terraform changes for ${params.ENVIRONMENT}?",
                    ok: 'Apply'
                )
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('day2') {
                    withCredentials([
                        usernamePassword(
                            credentialsId: 'aws-credentials',
                            usernameVariable: 'AWS_ACCESS_KEY_ID',
                            passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                        )
                    ]) {
                        sh '''
                            terraform apply -auto-approve tfplan
                        '''
                    }
                }
            }
        }

        stage('Terraform Output') {
            steps {
                dir('day2') {
                    sh '''
                        terraform output
                    '''
                }
            }
        }
    }
}
