pipeline {
    agent {
        docker {
            label 'dev'
            image 'hashicorp/terraform:latest'
            args '--entrypoint="" --user 0'
            reuseNode true
        }
    }

    parameters {
        choice(
            name: 'ENVIRONMENT',
            choices: ['sit', 'ppte', 'prod'],
            description: 'Select the environment'
        )
    }

    stages {

        stage('Terraform Init') {
            steps {
                dir('day2') {
                    sh '''
                        terraform version
                        terraform init
                    '''
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('day2') {
                    sh '''
                        echo "Environment: ${ENVIRONMENT}"
                        terraform plan -var-file=${ENVIRONMENT}.tfvars
                    '''
                }
            }
        }

        stage('Approval') {
            steps {
                input(
                    message: "Do you want to APPLY Terraform changes for ${params.ENVIRONMENT}?",
                    ok: 'Apply'
                )
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('day2') {
                    sh '''
                        terraform apply -auto-approve -var-file=${ENVIRONMENT}.tfvars
                    '''
                }
            }
        }

        stage('Terraform Output') {
            steps {
                dir('day2') {
                    sh 'terraform output'
                }
            }
        }
    }
}
